services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"  # Backend API
      - "5173:5173"  # Frontend dev server
    volumes:
      - ../logs:/app/logs
      - ../dev.sqlite3:/app/dev.sqlite3
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite:///app/dev.sqlite3
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 20s